name: Build and Test Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Lint for Firefox
        if: matrix.browser == 'firefox'
        run: web-ext lint

      - name: Build extension
        run: |
          mkdir -p artifacts
          if [ "${{ matrix.browser }}" = "firefox" ]; then
            # Firefox: Build V2 only
            cp manifest-v2.json manifest.json
            web-ext build --overwrite-dest
            mv web-ext-artifacts/*.zip artifacts/vt-keyboard-extension.xpi
            cp manifest-v3.json manifest.json
          else
            # Chromium: Build both V2 and V3
            # Build V3 first
            web-ext build --overwrite-dest
            mv web-ext-artifacts/*.zip artifacts/vt-keyboard-extension-v3.zip
            # Build V2
            cp manifest-v2.json manifest.json
            web-ext build --overwrite-dest
            mv web-ext-artifacts/*.zip artifacts/vt-keyboard-extension-v2.zip
            cp manifest-v3.json manifest.json
          fi

      - name: Upload Firefox artifact
        if: matrix.browser == 'firefox'
        uses: actions/upload-artifact@v4
        with:
          name: vt-keyboard-extension-firefox
          path: artifacts/vt-keyboard-extension.xpi

      - name: Upload Chromium V3 artifact
        if: matrix.browser == 'chromium'
        uses: actions/upload-artifact@v4
        with:
          name: vt-keyboard-extension-chromium-v3
          path: artifacts/vt-keyboard-extension-v3.zip

      - name: Upload Chromium V2 artifact
        if: matrix.browser == 'chromium'
        uses: actions/upload-artifact@v4
        with:
          name: vt-keyboard-extension-chromium-v2
          path: artifacts/vt-keyboard-extension-v2.zip